apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: location
spec:
  replicas: 2
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      serviceAccount: location
      containers:
      - name: webapp
        image: 790946953677.dkr.ecr.us-east-1.amazonaws.com/location:latest
        command:
          - ./app
          - -region
          - us-east-1
          - -tokenEndpoint
          - http://token.dev.svc.cluster.local
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: location
  namespace: dev
spec:
  selector:
    app: location
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: location
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: location
  minReplicas: 2
  maxReplicas: 64
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 40
